### ISSUE TITLE
RateLimitList.setRateLimit is checking for "user" not "application" 

### ISSUE THREAD

**Issue by ryanhaveson** [taycaldwell/riot-api-java#108]
From: https://developer.riotgames.com/rate-limiting.html:

X-Rate-Limit-Type returns, "method", "service", or "application".  RateLimitList was checking for "user" not "application".  As a result, when rate limit has been exceeded, subsequent calls are not taking advantage of the RateLimitList capability.

**Comment by Linnun** [comment]
The rate limit system seems to have undergone a few changes.

Did you get to test this rate limit change?

**Comment by ryanhaveson** [comment]
I didn’t do a lot of testing/examining of the code, but here is what I did:

I did a loop that triggered the rate limit response code, then in the try handler I verified that it returned the RespectedRateLimitException.

If you would like, I can make a unit test and submit that, but it will have to be later in the week.


try {
   for (int i = 0; i < 200; i++) {
      Summoner summoner = api.getSummonerByName(Platform.NA, "tryndamere");
      System.out.println("Name: " + summoner.getName() + ", ID: " + summoner.getId());
   }
} catch (RateLimitException e) {
   System.out.println("we caught the exception, and are trying again");
   Summoner summoner = api.getSummonerByName(Platform.NA, "tryndamere");
   System.out.println("Name: " + summoner.getName() + ", ID: " + summoner.getId());
}


Console output:

Exception in thread "main" net.rithms.riot.api.request.ratelimit.RespectedRateLimitException: Rate limit exceeded (Respected; Retry After: 113)
we caught the exception, and are trying again
                at net.rithms.riot.api.request.Request.respectRateLimit(Request.java:417)
                at net.rithms.riot.api.request.Request.execute(Request.java:136)
                at net.rithms.riot.api.request.Request.<init>(Request.java:100)
                at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:52)
                at net.rithms.riot.api.RiotApi.getSummonerByName(RiotApi.java:1621)
                at SimpleExample.main(SimpleExample.java:24)

**Comment by Linnun** [comment]
Thank you for your effort, I'll merge the pull request :) I don't think that having a unit test dedicated to trigger the rate limit would be a very good idea. It's good to have it tested though :)
