### ISSUE TITLE
Getting Started Difficulties

### ISSUE THREAD

**Issue by ASchwad** [taycaldwell/riot-api-java#127]
Hey taycaldwell, 

first: Great job developing this Library, looks really good!

My Problem:
I've imported the stated packages and Im trying your first example 
//Api Code cut out
Summoner summoner = api.getSummonerByName(Platform.EUW, "elthenlox");
System.out.println("Name: " + summoner.getName());
System.out.println("Summoner ID: " + summoner.getId());
System.out.println("Account ID: " + summoner.getAccountId());
System.out.println("Summoner Level: " + summoner.getSummonerLevel());
System.out.println("Profile Icon ID: " + summoner.getProfileIconId());

I get the following exception:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/JsonSyntaxException
	at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:52)
	at net.rithms.riot.api.RiotApi.getSummonerByName(RiotApi.java:1593)
	at tryout.Main.main(Main.java:28)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonSyntaxException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 3 more

Thanks in advance for your help!

Best Regards
Alex

**Comment by taycaldwell** [comment]
Hey Alex,

This project requires another library called Gson. Try including the jar in your project, or through maven/grade if you use one of those tools.

Let me know if you run into any further issues after including Gson in your project.

**Comment by ASchwad** [comment]
Wow thanks for the fast response.

Works now with Gson! Thanks a lot
