### ISSUE TITLE
getLeagueById throws RiotApiException

### ISSUE THREAD

**Issue by GPSforLEGENDS** [taycaldwell/riot-api-java#142]
I tried to get all player in my League so i used:

`LeagueList games  = api.getLeagueById(Platform.EUW, "d6576fc0-222c-11e8-8044-c81f66dacb22");`

but this throws the following exception:
`net.rithms.riot.api.RiotApiException: Failed to parse the JSON response
	at net.rithms.riot.api.request.Request.getDto(Request.java:288)
	at net.rithms.riot.api.request.Request.getDto(Request.java:252)
	at net.rithms.riot.api.EndpointManager.callMethodAndReturnDto(EndpointManager.java:53)
	at net.rithms.riot.api.RiotApi.getLeagueById(RiotApi.java:1467)
	at xyz.GPSforLEGENDS.main.LoLPredict.main(LoLPredict.java:29)`

The league ID should be correct because it works if i use the ID on https://developer.riotgames.com/api-methods/#league-v4/GET_getLeagueById

**Comment by Linnun** [comment]
It looks like some of the fields have been renamed for the v4 endpoints. In particular all the playerOrTeamId stuff has been renamed to summonerId, since ranked teams don't exist anymore.

I have pushed some changes. Please let me know if it works for you after pulling the latest changes. Cheers!
