### ISSUE TITLE
NumberFormatException when trying to call getMatch()

### ISSUE THREAD

**Issue by Nauschi** [taycaldwell/riot-api-java#152]
Hi,

I am getting a NumberFormatException whenever I try to call api.getMatch(platform, gameId).

It's because the JsonReader tries to parse the summonerId, which is a String, first to a long and then to a double. I have also noticed, that in the Player DTO the summonerId is of type long? But isn't the summonerId always returned encrypted and thus needs to be a String?

`Caused by: java.lang.NumberFormatException: For input string: "ENCRYPTED SUMMONER ID HERE"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:549)
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:977)
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:325)`

Thanks for any help in advance.

**Comment by Nauschi** [comment]
Changing the type of summonerId in the Player DTO class from long to String fixed the issue.
